import { CardAppliedForJob, CustomAlert, CustomLoading, MainLayout } from '../components';
import withAuth from '../components/withAuth';
import { useQuery, useSubscription } from '@apollo/client';
import { JobState } from '../interfaces';
import { useAppDispatch, useAppSelector } from '../hooks';
import { useEffect } from 'react';
import { listJobs } from '../redux';
import { useUserId } from '@nhost/react';
import { GET_JOBS_APPLIES_BY_USER, SUB_APPLIES } from '../graphql';
import { Grid } from '@nextui-org/react';

const AppliesPage = () => {

    return (
        <MainLayout title='LinkTree | My applies'>
            <MyApplies />
        </MainLayout>
    )
}
export default withAuth(AppliesPage)

// Generated by https://quicktype.io



export const MyApplies = () => {
    // TODO: refactor, this logic's component looks like the same in the page/index
    const id = useUserId();
    const { data, loading, error } = useQuery<{ post_user: { post: JobState[] }[] }>(GET_JOBS_APPLIES_BY_USER, { variables: { id } })
    const dispatch = useAppDispatch()
    const { appliedJobs } = useAppSelector(state => state.job)

    useSubscription(SUB_APPLIES, {
        variables: { id },
        onData: ({ data, client }) => {
            const newData = data.data.post_user.map((post: { post: JobState[] }) => {
                if (post.post[0]?.id) return post.post[0]
            })

            dispatch(listJobs({
                input: 'appliedJobs',
                jobs: newData.filter(Boolean)
            }))

            client.writeQuery({
                query: GET_JOBS_APPLIES_BY_USER,
                variables: { id },
                data: {
                    ...data.data
                }
            })
        }
    })

    useEffect(() => {
        if (data?.post_user && !appliedJobs) {
            dispatch(listJobs({
                input: 'appliedJobs',
                jobs: data.post_user.map(data => { return data.post[0] })
            }))
        }
    }, [data])

    if (loading || !appliedJobs) return <CustomLoading msg='Loading your applies for jobs' />

    if (error && !data?.post_user) return <CustomAlert msg={error.message} />

    return (
        <Grid.Container gap={5}>
            {
                appliedJobs.map(job => (
                    <Grid key={job.id}>
                        <CardAppliedForJob {...job} />
                    </Grid>
                ))
            }
        </Grid.Container>
    )
}